name: Upload exported model to S3

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-southeast-2
  AWS_BUCKET_NAME: s3://sightdata-tm/Model_Weights/yolov8_seg/

jobs:
  upload-image:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          
      - name: Install requirements
        shell: bash  # for Windows compatibility
        run: |
          python -m pip install --upgrade pip wheel
          if [ "${{ matrix.torch }}" == "1.8.0" ]; then
              pip install -e . torch==1.8.0 torchvision==0.9.0 pytest --extra-index-url https://download.pytorch.org/whl/cpu
          else
              pip install -e . pytest --extra-index-url https://download.pytorch.org/whl/cpu
          fi
          
      - name: Export model
        shell: bash
        run: |
          yolo export model=yolov8x-seg.pt format=onnx device=0
          
      - name: Download requirements
        shell: bash
        run: |      
          aws s3 cp yolov8x-seg.onnx $AWS_BUCKET_NAME
