name: Upload exported model to S3

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-southeast-2\
  AWS_BUCKET_NAME: s3://sightdata-tm/Model_Weights/yolov8_seg/

jobs:
  upload-image:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          
      - name: Download requirements
        run: |
          pip install -e .
          
      - name: Export model
        shell: python
        run: |
          from ultralytics import YOLO

          # Load a model
          model = YOLO('yolov8x-seg.pt')  # load an official model
          
          # Export the model
          model.export(format='onnx')
          
      - name: Download requirements
        shell: bash
        run: |      
          aws s3 cp yolov8x-seg.onnx $AWS_BUCKET_NAME
