name: Upload exported model to S3

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-southeast-2

jobs:
  upload-image:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          
      - name: Download requirements
        run: |
          pip install -e .
          

      - name: Export and push model to S3
        env:
          AWS_BUCKET_NAME: s3://sightdata-tm/Model_Weights/yolov8_seg/
        run: |
          yolo export model=yolov8x-seg.pt format=onnx device=0
          aws s3 cp yolov8x-seg.onnx AWS_BUCKET_NAME
